from omni_npu.v1.layers.rotary_embedding.rotary_embedding_torch_npu import NPURotaryEmbedding
from omni_npu.v1.layers.rotary_embedding.linear_scaling_rope import NPULinearScalingRotaryEmbedding
from omni_npu.v1.layers.rotary_embedding.llama3_rope import NPULlama3RotaryEmbedding
from omni_npu.v1.layers.rotary_embedding.deepseek_scaling_rope import NPUDeepseekScalingRotaryEmbedding
from omni_npu.v1.layers.rotary_embedding.yarn_scaling_rope import NPUYaRNScalingRotaryEmbedding